# Generated by Django 6.0.7 on 2026-08-05 01:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0002_acciontratamiento_origen_riesgo_activo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlISO27001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(help_text='Ej. 5.1, 8.16', max_length=10, unique=True)),
                ('categoria', models.CharField(choices=[('ORGANIZACIONAL', 'Organizacional (5.x)'), ('PERSONAS', 'Personas (6.x)'), ('FISICO', 'Físico (7.x)'), ('TECNOLOGICO', 'Tecnológico (8.x)')], max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('aplicable', models.BooleanField(default=True, help_text='Según la Declaración de Aplicabilidad (SoA)')),
                ('justificacion_aplicabilidad', models.TextField(blank=True, help_text='Por qué aplica o no aplica a SUIIN/CRIC')),
                ('estado_implementacion', models.CharField(choices=[('NO_IMPLEMENTADO', 'No implementado'), ('PARCIAL', 'Implementación parcial'), ('IMPLEMENTADO', 'Implementado'), ('NO_APLICA', 'No aplica')], default='NO_IMPLEMENTADO', max_length=20)),
                ('politica_referencia', models.CharField(blank=True, help_text='Ej. POL-SI-012 (referencia libre al catálogo de políticas)', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Control ISO 27001 (Anexo A)',
                'verbose_name_plural': 'Controles ISO 27001 (Anexo A)',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='acciontratamiento',
            name='control_iso27001',
            field=models.CharField(blank=True, help_text='Texto libre heredado del Excel original', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalacciontratamiento',
            name='control_iso27001',
            field=models.CharField(blank=True, help_text='Texto libre heredado del Excel original', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalriesgocontextual',
            name='controles_iso',
            field=models.TextField(blank=True, help_text='Texto libre heredado del Excel original'),
        ),
        migrations.AlterField(
            model_name='riesgocontextual',
            name='controles_iso',
            field=models.TextField(blank=True, help_text='Texto libre heredado del Excel original'),
        ),
        migrations.AddField(
            model_name='acciontratamiento',
            name='controles_iso_vinculados',
            field=models.ManyToManyField(blank=True, help_text='Vínculo estructurado al catálogo de controles (usar en vez del texto libre para nuevos registros)', related_name='acciones_tratamiento', to='riesgos.controliso27001'),
        ),
        migrations.AddField(
            model_name='riesgocontextual',
            name='controles_iso_vinculados',
            field=models.ManyToManyField(blank=True, help_text='Vínculo estructurado al catálogo de controles (usar en vez del texto libre para nuevos registros)', related_name='riesgos_contextuales', to='riesgos.controliso27001'),
        ),
        migrations.CreateModel(
            name='HistoricalControlISO27001',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('creado_en', models.DateTimeField(blank=True, editable=False)),
                ('actualizado_en', models.DateTimeField(blank=True, editable=False)),
                ('codigo', models.CharField(db_index=True, help_text='Ej. 5.1, 8.16', max_length=10)),
                ('categoria', models.CharField(choices=[('ORGANIZACIONAL', 'Organizacional (5.x)'), ('PERSONAS', 'Personas (6.x)'), ('FISICO', 'Físico (7.x)'), ('TECNOLOGICO', 'Tecnológico (8.x)')], max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('aplicable', models.BooleanField(default=True, help_text='Según la Declaración de Aplicabilidad (SoA)')),
                ('justificacion_aplicabilidad', models.TextField(blank=True, help_text='Por qué aplica o no aplica a SUIIN/CRIC')),
                ('estado_implementacion', models.CharField(choices=[('NO_IMPLEMENTADO', 'No implementado'), ('PARCIAL', 'Implementación parcial'), ('IMPLEMENTADO', 'Implementado'), ('NO_APLICA', 'No aplica')], default='NO_IMPLEMENTADO', max_length=20)),
                ('politica_referencia', models.CharField(blank=True, help_text='Ej. POL-SI-012 (referencia libre al catálogo de políticas)', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Control ISO 27001 (Anexo A)',
                'verbose_name_plural': 'historical Controles ISO 27001 (Anexo A)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
