# Generated by Django 6.0.7 on 2026-08-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0003_controliso27001_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciontratamiento',
            name='fecha_limite',
            field=models.DateField(blank=True, help_text='Fecha límite absoluta (opcional). Para acciones importadas del PTR original el plazo suele ser relativo — use fecha_limite_texto en ese caso; para acciones nuevas creadas desde la app, prefiera esta fecha real para habilitar alertas.', null=True),
        ),
        migrations.AddField(
            model_name='historicalacciontratamiento',
            name='fecha_limite',
            field=models.DateField(blank=True, help_text='Fecha límite absoluta (opcional). Para acciones importadas del PTR original el plazo suele ser relativo — use fecha_limite_texto en ese caso; para acciones nuevas creadas desde la app, prefiera esta fecha real para habilitar alertas.', null=True),
        ),
    ]
