# Generated by Django 6.0.7 on 2026-08-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0004_acciontratamiento_fecha_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciontratamiento',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='activo',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='campanaredteam',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='controliso27001',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalacciontratamiento',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcampanaredteam',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontroliso27001',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalplantratamientoriesgos',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalriesgoactivo',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalriesgocontextual',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalvulnerabilidad',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='plantratamientoriesgos',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='puertoservicio',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='riesgoactivo',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='riesgocontextual',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='importado_en',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
