# Generated by Django 6.0.7 on 2026-08-19 14:26

import django.db.models.deletion
import riesgos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('riesgos', '0006_backfill_importado_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('importado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('archivo', models.FileField(upload_to=riesgos.models.ruta_evidencia, validators=[riesgos.models.validar_extension_evidencia, riesgos.models.validar_tamano_evidencia])),
                ('nombre_original', models.CharField(blank=True, max_length=255)),
                ('tipo_archivo', models.CharField(blank=True, choices=[('IMAGEN', 'Imagen'), ('PDF', 'PDF'), ('DOCUMENTO', 'Documento'), ('OTRO', 'Otro')], editable=False, max_length=15)),
                ('tamano_bytes', models.PositiveIntegerField(default=0, editable=False)),
                ('descripcion', models.CharField(blank=True, help_text='Qué muestra esta evidencia', max_length=500)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='riesgos_evi_content_31c13f_idx')],
            },
        ),
    ]
