# Generated by Django 6.0.7 on 2026-08-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0007_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='inventario_id',
            field=models.PositiveIntegerField(blank=True, help_text='PK del activo correspondiente en la Plataforma SUIIN (Inventario) — null si aún no está vinculado. Ver comando sincronizar_activos_inventario.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='inventario_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='PK del activo correspondiente en la Plataforma SUIIN (Inventario) — null si aún no está vinculado. Ver comando sincronizar_activos_inventario.', null=True),
        ),
    ]
