# Generated by Django 6.0.7 on 2026-08-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0008_activo_inventario_id_historicalactivo_inventario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalriesgocontextual',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('CERRADO', 'Cerrado'), ('FALSO_POSITIVO', 'Falso positivo'), ('ACEPTADO', 'Aceptado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalriesgocontextual',
            name='fecha_limite',
            field=models.DateField(blank=True, help_text="Fecha límite absoluta (opcional) del ítem más urgente de 'plazo'. Habilita las alertas de vencimiento para este riesgo contextual.", null=True),
        ),
        migrations.AddField(
            model_name='riesgocontextual',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('CERRADO', 'Cerrado'), ('FALSO_POSITIVO', 'Falso positivo'), ('ACEPTADO', 'Aceptado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='riesgocontextual',
            name='fecha_limite',
            field=models.DateField(blank=True, help_text="Fecha límite absoluta (opcional) del ítem más urgente de 'plazo'. Habilita las alertas de vencimiento para este riesgo contextual.", null=True),
        ),
        migrations.AlterField(
            model_name='historicalriesgocontextual',
            name='estado_actual',
            field=models.CharField(blank=True, help_text="Texto libre heredado del Excel original (ej. 'SIN CONTROL') — use 'estado' para el campo estructurado que alimenta las alertas de vencimiento.", max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalriesgocontextual',
            name='plazo',
            field=models.CharField(blank=True, help_text="Texto libre heredado del Excel — puede contener varios subplazos relativos (ej. '0–30 días protocolo, 0–15 días lámina vidrio'). Use fecha_limite para el plazo más urgente de los mencionados, si quiere que entre en las alertas.", max_length=255),
        ),
        migrations.AlterField(
            model_name='riesgocontextual',
            name='estado_actual',
            field=models.CharField(blank=True, help_text="Texto libre heredado del Excel original (ej. 'SIN CONTROL') — use 'estado' para el campo estructurado que alimenta las alertas de vencimiento.", max_length=50),
        ),
        migrations.AlterField(
            model_name='riesgocontextual',
            name='plazo',
            field=models.CharField(blank=True, help_text="Texto libre heredado del Excel — puede contener varios subplazos relativos (ej. '0–30 días protocolo, 0–15 días lámina vidrio'). Use fecha_limite para el plazo más urgente de los mencionados, si quiere que entre en las alertas.", max_length=255),
        ),
    ]
