# Generated by Django 6.0.7 on 2026-08-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0010_poblar_estado_riesgo_contextual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campanaredteam',
            name='riesgos_criticos',
            field=models.PositiveIntegerField(default=0, help_text='Foto AL MOMENTO DE LA CAMPAÑA — no se actualiza sola después. Ver riesgos_actuales_por_nivel para el conteo en vivo.'),
        ),
        migrations.AlterField(
            model_name='historicalcampanaredteam',
            name='riesgos_criticos',
            field=models.PositiveIntegerField(default=0, help_text='Foto AL MOMENTO DE LA CAMPAÑA — no se actualiza sola después. Ver riesgos_actuales_por_nivel para el conteo en vivo.'),
        ),
    ]
