# Generated by Django 6.0.7 on 2026-08-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0011_alter_campanaredteam_riesgos_criticos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('importado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('categoria', models.CharField(choices=[('TIPO_ACTIVO', 'Tipo de activo'), ('RESPONSABLE_RIESGO', 'Responsable sugerido (riesgo por activo)'), ('RESPONSABLE_ACCION', 'Responsable (acción de tratamiento)'), ('FUENTE_HALLAZGO', 'Fuente del hallazgo (acción de tratamiento)'), ('PLAZO_ACCION', 'Plazo (acción de tratamiento)')], max_length=30)),
                ('valor', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Los valores desactivados dejan de sugerirse en el formulario, pero los registros que ya los usan no cambian.')),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Valor de catálogo',
                'verbose_name_plural': 'Valores de catálogo',
                'ordering': ['categoria', 'orden', 'valor'],
                'unique_together': {('categoria', 'valor')},
            },
        ),
    ]
