# Generated by Django 6.0.7 on 2026-08-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0012_catalogovalor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnicaMitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('importado_en', models.DateTimeField(blank=True, editable=False, null=True)),
                ('codigo', models.CharField(help_text='Ej. T1190, TA0001, T1055.001', max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(blank=True, choices=[('TA', 'Táctica'), ('TE', 'Técnica'), ('ST', 'Subtécnica')], max_length=2)),
                ('tacticas', models.CharField(blank=True, max_length=300)),
                ('codigo_padre', models.CharField(blank=True, max_length=20)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Técnica MITRE ATT&CK',
                'verbose_name_plural': 'Técnicas MITRE ATT&CK',
                'ordering': ['codigo'],
            },
        ),
    ]
