# Generated by Django 6.0.7 on 2026-08-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0013_tecnicamitre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogovalor',
            name='categoria',
            field=models.CharField(choices=[('TIPO_ACTIVO', 'Tipo de activo'), ('RESPONSABLE_RIESGO', 'Responsable sugerido (riesgo por activo)'), ('RESPONSABLE_ACCION', 'Responsable (acción de tratamiento)'), ('FUENTE_HALLAZGO', 'Fuente del hallazgo (acción de tratamiento)'), ('PLAZO_ACCION', 'Plazo (acción de tratamiento)'), ('SOLUCION_VULN', 'Solución recomendada (vulnerabilidad)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='catalogovalor',
            name='valor',
            field=models.TextField(help_text="Corto para catálogos como 'Tipo de activo'; puede ser un párrafo largo para 'Solución recomendada' (texto de OpenVAS)."),
        ),
    ]
