# Generated by Django 6.0.7 on 2026-08-24 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0014_alter_catalogovalor_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acciontratamiento',
            name='origen_riesgo_contextual',
            field=models.ForeignKey(blank=True, help_text='Riesgo contextual (amenaza interna, legal, físico) que originó esta acción, si aplica — antes solo Vulnerabilidad y RiesgoActivo tenían este vínculo; los 7 riesgos contextuales quedaban fuera del ciclo hallazgo→acción→cierre trazado, sin forma de saber qué acción atendía cuál riesgo contextual.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_generadas', to='riesgos.riesgocontextual'),
        ),
        migrations.AddField(
            model_name='historicalacciontratamiento',
            name='origen_riesgo_contextual',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Riesgo contextual (amenaza interna, legal, físico) que originó esta acción, si aplica — antes solo Vulnerabilidad y RiesgoActivo tenían este vínculo; los 7 riesgos contextuales quedaban fuera del ciclo hallazgo→acción→cierre trazado, sin forma de saber qué acción atendía cuál riesgo contextual.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='riesgos.riesgocontextual'),
        ),
    ]
