# Generated by Django 6.0.7 on 2026-09-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0017_espacio_codigo_por_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='espacio_codigo',
            field=models.CharField(db_index=True, default='organizacion', help_text='Espacio de datos del usuario (aislamiento multi-tenant ligero).', max_length=60),
        ),
        migrations.AlterField(
            model_name='campanaredteam',
            name='espacio_codigo',
            field=models.CharField(db_index=True, default='organizacion', help_text='Espacio de datos del usuario (aislamiento multi-tenant ligero).', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalactivo',
            name='espacio_codigo',
            field=models.CharField(db_index=True, default='organizacion', help_text='Espacio de datos del usuario (aislamiento multi-tenant ligero).', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalactivo',
            name='id_activo',
            field=models.CharField(help_text='Ej. RED-012, SI-06', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalactivo',
            name='inventario_id',
            field=models.PositiveIntegerField(blank=True, help_text='PK del activo correspondiente en la Plataforma SUIIN (Inventario) — null si aún no está vinculado. Ver comando sincronizar_activos_inventario.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalcampanaredteam',
            name='espacio_codigo',
            field=models.CharField(db_index=True, default='organizacion', help_text='Espacio de datos del usuario (aislamiento multi-tenant ligero).', max_length=60),
        ),
        migrations.AlterField(
            model_name='historicalcampanaredteam',
            name='nombre',
            field=models.CharField(help_text='Ej. SUIIN-CENSO', max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalplantratamientoriesgos',
            name='referencia',
            field=models.CharField(help_text='Ej. SUIIN-SGSI-PTR-001 v1.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalriesgocontextual',
            name='id_riesgo_contextual',
            field=models.CharField(help_text='Ej. RC-03', max_length=10),
        ),
    ]
