"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-dev-key-cambiar-en-produccion')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
# 'inventario' (el nombre del servicio en docker-compose.yml) SIEMPRE debe
# poder resolverse como Host válido, sin depender de que alguien lo agregue a
# mano en DJANGO_ALLOWED_HOSTS — hallazgo real: sincronizar_activos_inventario
# (en riesgos) llama a http://inventario:8000/api/ directo, contenedor a
# contenedor, sin pasar por nginx (que sí reescribe el Host al del dominio
# público) — con Host: inventario:8000, Django lo rechazaba con 400 Bad
# Request ("Invalid HTTP_HOST header") al no estar en la lista.
for _host_interno in ('inventario', 'localhost', '127.0.0.1'):
    if _host_interno not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host_interno)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'django_filters',
    'simple_history',
    'axes',
    'inventario',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'inventario.middleware.SesionPlataformaMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    'axes.middleware.AxesMiddleware',  # SIEMPRE al final (requisito de django-axes)
]

# Endurecimiento del login (control de acceso 5.17/8.5): bloqueo tras
# intentos fallidos, por combinación de usuario + IP para no bloquear a
# toda una VLAN por un solo usuario con la contraseña equivocada. Ver
# README-DESPLIEGUE.md sección 8.9 — desde la unificación, este login
# protege el acceso a los dos módulos (Inventario y, a través de él, RBAC).
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AXES_FAILURE_LIMIT = 5

# ---------------------------------------------------------------------------
# JWT de plataforma — sesión única con SUIIN-SGSI-RIESGOS
# ---------------------------------------------------------------------------
# El Inventario ya es la fuente de identidad y roles del despliegue unificado
# (ver permisos.py y las vistas sesion_info_v2/auth_check_rbac). En vez de que
# cada módulo nuevo tenga su propio login separado, el Inventario EMITE un JWT
# firmado que los demás módulos pueden VERIFICAR localmente (sin llamar de
# vuelta al Inventario en cada petición) — ver inventario/jwt_plataforma.py y,
# del lado que lo consume, riesgos/backend/riesgos/auth_jwt.py.
#
# JWT_SHARED_SECRET debe ser IDÉNTICO en ambos servicios — es un secreto
# compartido, a propósito, a diferencia de DJANGO_SECRET_KEY (que si debe ser
# distinto por app; ver README-DESPLIEGUE.md sección 11 y docker-compose.yml).
JWT_SHARED_SECRET = os.environ.get('JWT_SHARED_SECRET', '')
JWT_ALGORITHM = 'HS256'
JWT_EXPIRACION_MINUTOS = int(os.environ.get('JWT_EXPIRACION_MINUTOS', '30'))
JWT_ISSUER = 'suiin-inventario'
# Lista ANIDADA (una sola lista adentro) — significa "bloquear por la
# COMBINACIÓN usuario+IP juntos". La forma plana ['username', 'ip_address']
# (sin anidar, como estaba antes) significa otra cosa distinta en
# django-axes: "bloquear por usuario O por IP, cada uno aparte" — con esa
# forma, una IP compartida (oficina, NAT) puede terminar bloqueada para todo
# el mundo aunque los intentos fallidos hayan sido de cuentas distintas,
# justo lo que el comentario de arriba decía que no debía pasar. Verificado
# en el código fuente de axes (axes/conf.py) y reproducido en vivo al
# construir la misma protección para SUIIN-SGSI-RIESGOS.
AXES_LOCKOUT_PARAMETERS = [['username', 'ip_address']]
AXES_COOLOFF_TIME = 1  # horas
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = 'registration/bloqueado.html'

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            # Modo WAL en vez del rollback journal por defecto: permite que
            # lecturas y escrituras no se bloqueen entre sí. Con gunicorn
            # --workers 3 (varios procesos, cada uno con su propia conexión
            # al mismo archivo .sqlite3), el modo por defecto es mucho más
            # propenso a "database is locked" bajo ráfagas de tráfico
            # concurrente — hallazgo real (2026-08-26): la verificación de
            # autorización de RBAC (auth_check_rbac, que lee la sesión desde
            # esta misma base) empezó a fallar intermitentemente justo en
            # ráfagas de tráfico simultáneo hacia el Inventario y riesgos.
            'init_command': 'PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;',
            # Respaldo: si aun así se topa con un lock momentáneo, espera
            # hasta 20s antes de fallar, en vez del valor por defecto de
            # sqlite3 (5s), que bajo una ráfaga real puede no alcanzar.
            'timeout': 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# --- Django REST Framework ---
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_PERMISSION_CLASSES': [
        'inventario.permisos.RolPermiso',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'inventario.sesion_plataforma.SesionPlataformaAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# --- Archivos subidos (diagramas, documentos de hoja de vida) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400
FILE_UPLOAD_MAX_MEMORY_SIZE = 26214400


# --- Endurecimiento de produccion (activo cuando DEBUG=False) ---
if not DEBUG:
    # Un solo indicador de si este despliegue ya tiene TLS real (propio o
    # terminado por un proxy delante), gobierna tanto la redirección como
    # las cookies Secure y HSTS. Antes, SESSION/CSRF_COOKIE_SECURE estaban
    # fijos en True solo con DEBUG=False, sin mirar si de verdad había TLS
    # — con el despliegue actual (sin TLS todavía, DJANGO_SSL_REDIRECT=False
    # como documenta .env.example) el navegador descartaba la cookie
    # csrftoken por venir marcada Secure sobre HTTP plano, y todo
    # POST/PUT/DELETE del Inventario quedaba rechazado con 403.
    TLS_ACTIVO = os.environ.get('DJANGO_SSL_REDIRECT', 'True').lower() in ('1', 'true', 'yes')
    SECURE_SSL_REDIRECT = TLS_ACTIVO
    SESSION_COOKIE_SECURE = TLS_ACTIVO
    CSRF_COOKIE_SECURE = TLS_ACTIVO
    if TLS_ACTIVO:
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # SAMEORIGIN (no DENY): el Inventario incrusta RBAC y Riesgos en <iframe>
    # propios (mismo origen, vía el gateway nginx de la plataforma) — y ambos
    # módulos, si su sesión no está sincronizada, redirigen de vuelta acá
    # (/login/) como respaldo. Con DENY, esa página de respaldo no se podía
    # mostrar dentro de ESE iframe tampoco, y el navegador la bloqueaba
    # mostrando un ícono de archivo roto en vez de la pantalla de login —
    # hallazgo real, reportado con captura, diagnosticado por el mensaje
    # exacto en la consola del navegador: "Refused to display '.../ ' in a
    # frame because it set 'X-Frame-Options' to 'deny'." RBAC ya tenía este
    # mismo ajuste hecho correctamente (ver rbac/auth.py); acá se había
    # quedado en el valor por defecto de Django. Un origen externo sigue sin
    # poder enmarcar el Inventario — SAMEORIGIN no lo permite.
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('DJANGO_CSRF_TRUSTED', '').split(',') if o]

# --- Base de datos: PostgreSQL si se define DATABASE_URL, si no SQLite ---
if os.environ.get('DJANGO_DB_ENGINE') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DJANGO_DB_NAME', 'suiin_inventario'),
            'USER': os.environ.get('DJANGO_DB_USER', 'suiin'),
            'PASSWORD': os.environ.get('DJANGO_DB_PASSWORD', ''),
            'HOST': os.environ.get('DJANGO_DB_HOST', '127.0.0.1'),
            'PORT': os.environ.get('DJANGO_DB_PORT', '5432'),
        }
    }

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

# --- Correo (notificaciones proactivas — README-DESPLIEGUE.md sección 10) ---
# Si no se configura DJANGO_EMAIL_HOST, se usa el backend de consola: los
# correos se imprimen en los logs del contenedor en vez de fallar. Así el
# comando `enviar_resumen_alertas` (y cualquier otro envío futuro) nunca
# rompe un despliegue que todavía no configuró SMTP — solo no envía nada
# de verdad hasta que se complete la configuración.
if os.environ.get('DJANGO_EMAIL_HOST'):
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('DJANGO_EMAIL_HOST')
    EMAIL_PORT = int(os.environ.get('DJANGO_EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('DJANGO_EMAIL_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('DJANGO_EMAIL_PASSWORD', '')
    EMAIL_USE_TLS = os.environ.get('DJANGO_EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_EMAIL_FROM', 'suiin-sgsi@cric.org.co')
# Uno o varios correos separados por coma; vacío = nadie configurado
# todavía (el comando lo detecta y avisa en vez de fallar en silencio).
ALERTAS_EMAIL_DESTINATARIOS = [
    e.strip() for e in os.environ.get('DJANGO_ALERTAS_EMAIL', '').split(',') if e.strip()
]

# ---------------------------------------------------------------------------
# Guardia contra secretos sin configurar — se niega a arrancar en vez de
# correr insegura en silencio.
# ---------------------------------------------------------------------------
# Hallazgo real de un despliegue: se copió .env.example a .env pero nunca se
# reemplazaron los valores de ejemplo (todos empiezan con "defina-" en la
# plantilla, a propósito, para que esta detección sea simple y confiable) —
# la aplicación arrancó igual, con DEBUG=False, usando como SECRET_KEY y
# JWT_SHARED_SECRET el mismo texto público que trae el repositorio. Cualquiera
# que haya visto el .env.example (es público) puede forjar sesiones, o un JWT
# que diga "soy Administrador" sin ninguna contraseña. Antes de esto, no había
# nada que detectara ese error — ahora sí, y de forma imposible de ignorar.
def _validar_secretos_configurados():
    marcadores_de_ejemplo = ('defina-', 'django-insecure-')
    a_revisar = {
        'DJANGO_SECRET_KEY': SECRET_KEY,
        'JWT_SHARED_SECRET': JWT_SHARED_SECRET,
    }
    con_placeholder = [
        nombre for nombre, valor in a_revisar.items()
        if valor and any(valor.startswith(m) for m in marcadores_de_ejemplo)
    ]
    if con_placeholder and not DEBUG:
        from django.core.exceptions import ImproperlyConfigured
        raise ImproperlyConfigured(
            "No se puede arrancar con DJANGO_DEBUG=False mientras estas variables sigan con "
            f"el valor de ejemplo de .env.example: {', '.join(con_placeholder)}. "
            "Genere un valor real y aleatorio para cada una (ej. "
            "`python3 -c \"import secrets; print(secrets.token_urlsafe(50))\"`) y actualice su "
            "archivo .env — ver README-DESPLIEGUE.md."
        )
    if con_placeholder and DEBUG:
        import warnings
        warnings.warn(
            f"⚠ Usando valores de ejemplo de .env.example para: {', '.join(con_placeholder)}. "
            "Esto es aceptable en desarrollo (DEBUG=True) pero NO debe llegar a producción.",
            stacklevel=2,
        )


_validar_secretos_configurados()
