# Generated by Django 6.0.7 on 2026-07-16 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmenazaMITRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: T1486, TA0040', max_length=20, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Amenaza MITRE ATT&CK',
                'verbose_name_plural': 'Amenazas MITRE ATT&CK',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ControlISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: 8.13, POL-SI-009', max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Control ISO / Politica',
                'verbose_name_plural': 'Controles ISO / Politicas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='RolMCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(help_text='Ej: CM, DOS, DBA', max_length=10, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Rol MCA',
                'verbose_name_plural': 'Roles MCA',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'VLAN',
                'verbose_name_plural': 'VLANs',
                'ordering': ['etiqueta'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Zona de red',
                'verbose_name_plural': 'Zonas de red',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_activo', models.CharField(max_length=30, unique=True, verbose_name='ID Activo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del activo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion / Funcion')),
                ('clase', models.CharField(choices=[('INFRA', 'Infraestructura de red'), ('SIST', 'Sistema de informacion')], max_length=6)),
                ('clasificacion_si', models.CharField(blank=True, choices=[('ALTA', 'Altamente Confidencial'), ('CONF', 'Confidencial'), ('INT', 'Uso Interno'), ('PUB', 'Publico')], max_length=5, verbose_name='Clasificacion SI')),
                ('confidencialidad', models.IntegerField(blank=True, choices=[(0, '0 - N/A'), (1, '1 - Bajo'), (2, '2 - Medio'), (3, '3 - Alto'), (4, '4 - Critico')], null=True)),
                ('integridad', models.IntegerField(blank=True, choices=[(0, '0 - N/A'), (1, '1 - Bajo'), (2, '2 - Medio'), (3, '3 - Alto'), (4, '4 - Critico')], null=True)),
                ('disponibilidad', models.IntegerField(blank=True, choices=[(0, '0 - N/A'), (1, '1 - Bajo'), (2, '2 - Medio'), (3, '3 - Alto'), (4, '4 - Critico')], null=True)),
                ('valor', models.IntegerField(blank=True, null=True, verbose_name='Valor (C+I+D)')),
                ('nivel_riesgo', models.CharField(blank=True, choices=[('CRIT', 'Critico'), ('ALTO', 'Alto'), ('MED', 'Medio'), ('BAJO', 'Bajo'), ('SIN', 'Sin valorar')], default='SIN', max_length=5)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('IMP', 'En implementacion'), ('INA', 'Inactivo / No operacion'), ('RET', 'Retirado')], default='ACT', max_length=4)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('notas_seguridad', models.TextField(blank=True, verbose_name='Notas de seguridad')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('amenazas', models.ManyToManyField(blank=True, related_name='activos', to='inventario.amenazamitre')),
                ('controles', models.ManyToManyField(blank=True, related_name='activos', to='inventario.controliso')),
            ],
            options={
                'verbose_name': 'Activo',
                'verbose_name_plural': 'Activos',
                'ordering': ['id_activo'],
            },
        ),
        migrations.CreateModel(
            name='AccesoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('C', 'Completo'), ('M', 'Modificacion'), ('L', 'Lectura')], max_length=1)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.rolmca')),
            ],
            options={
                'verbose_name': 'Acceso por rol (MCA)',
                'verbose_name_plural': 'Accesos por rol (MCA)',
            },
        ),
        migrations.CreateModel(
            name='ActivoInfraestructura',
            fields=[
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='infraestructura', serialize=False, to='inventario.activo')),
                ('tipo', models.CharField(blank=True, max_length=60)),
                ('subtipo', models.CharField(blank=True, max_length=120, verbose_name='Subtipo / Categoria')),
                ('ip_segmento', models.CharField(blank=True, max_length=120, verbose_name='IP / Segmento')),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('serial_placa', models.CharField(blank=True, max_length=120, verbose_name='Serial / Placa')),
                ('vlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.vlan')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.zona')),
            ],
            options={
                'verbose_name': 'Activo de infraestructura',
                'verbose_name_plural': 'Activos de infraestructura',
            },
        ),
        migrations.CreateModel(
            name='SistemaInformacion',
            fields=[
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sistema', serialize=False, to='inventario.activo')),
                ('estado_operativo', models.CharField(choices=[('OP', 'En operacion'), ('IMP', 'En implementacion'), ('NO', 'No operacion'), ('SD', 'Sin dato')], default='SD', max_length=4)),
                ('backend', models.CharField(blank=True, max_length=120, verbose_name='Backend (Framework)')),
                ('frontend', models.CharField(blank=True, max_length=120)),
                ('schema_bd', models.CharField(blank=True, max_length=120, verbose_name='Schema BD')),
                ('api_rest_nativa', models.BooleanField(blank=True, null=True)),
                ('integracion_gateway', models.CharField(blank=True, max_length=120)),
                ('estado_documentacion', models.CharField(blank=True, max_length=255)),
                ('sistema_mca_equivalente', models.CharField(blank=True, max_length=120, verbose_name='Sistema MCA equivalente')),
                ('servidor_virtual', models.CharField(blank=True, max_length=40)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('priorizar_analisis', models.CharField(choices=[('ALTA', 'Alta - Inmediata'), ('MED', 'Media - Proxima fase'), ('BAJA', 'Baja - Pendiente'), ('SIN', 'Sin priorizar')], default='SIN', max_length=5)),
                ('gw_validacion_jwt', models.BooleanField(blank=True, null=True)),
                ('gw_sso', models.BooleanField(blank=True, null=True)),
                ('gw_cors', models.BooleanField(blank=True, null=True)),
                ('gw_inyeccion_roles', models.BooleanField(blank=True, null=True)),
                ('gw_refresh_token', models.BooleanField(blank=True, null=True)),
                ('gw_balanceo_carga', models.BooleanField(blank=True, null=True)),
                ('roles', models.ManyToManyField(blank=True, related_name='sistemas', through='inventario.AccesoRol', to='inventario.rolmca')),
            ],
            options={
                'verbose_name': 'Sistema de informacion',
                'verbose_name_plural': 'Sistemas de informacion',
            },
        ),
        migrations.AddField(
            model_name='accesorol',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.sistemainformacion'),
        ),
        migrations.AlterUniqueTogether(
            name='accesorol',
            unique_together={('sistema', 'rol')},
        ),
    ]
