# Generated by Django 6.0.7 on 2026-07-16 20:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_activo_area_responsable_activo_ciclo_vida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datacenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: DC-POPAYAN', max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('PRIN', 'Datacenter principal'), ('MINI', 'Mini-datacenter'), ('DR', 'Sitio de respaldo (DR)'), ('CLOUD', 'Nube / Colocation')], default='PRIN', max_length=6)),
                ('nivel_tier', models.CharField(choices=[('NA', 'No clasificado'), ('T1', 'Tier I'), ('T2', 'Tier II'), ('T3', 'Tier III'), ('T4', 'Tier IV')], default='NA', max_length=3)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, default='Colombia', max_length=60)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Centro de datos',
                'verbose_name_plural': 'Centros de datos',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='activoinfraestructura',
            name='rack',
            field=models.CharField(blank=True, max_length=40, verbose_name='Rack'),
        ),
        migrations.AddField(
            model_name='activoinfraestructura',
            name='unidad_rack',
            field=models.CharField(blank=True, help_text='Ej: U12-U14', max_length=20, verbose_name='Unidad de rack (U)'),
        ),
        migrations.AddField(
            model_name='historicalactivoinfraestructura',
            name='rack',
            field=models.CharField(blank=True, max_length=40, verbose_name='Rack'),
        ),
        migrations.AddField(
            model_name='historicalactivoinfraestructura',
            name='unidad_rack',
            field=models.CharField(blank=True, help_text='Ej: U12-U14', max_length=20, verbose_name='Unidad de rack (U)'),
        ),
        migrations.AddField(
            model_name='activo',
            name='datacenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='inventario.datacenter', verbose_name='Centro de datos'),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='datacenter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.datacenter', verbose_name='Centro de datos'),
        ),
        migrations.CreateModel(
            name='Diagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('TOPO', 'Topologia de red'), ('RACK', 'Diagrama de rack'), ('ARQ', 'Arquitectura'), ('FLUJO', 'Diagrama de flujo'), ('PLANO', 'Plano fisico'), ('OTRO', 'Otro')], default='TOPO', max_length=6)),
                ('archivo', models.FileField(upload_to='diagramas/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('activos', models.ManyToManyField(blank=True, related_name='diagramas', to='inventario.activo')),
                ('datacenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagramas', to='inventario.datacenter')),
            ],
            options={
                'verbose_name': 'Diagrama / Topologia',
                'verbose_name_plural': 'Diagramas / Topologias',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='EventoHojaVida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_evento', models.CharField(choices=[('ALTA', 'Alta / Puesta en marcha'), ('MPRE', 'Mantenimiento preventivo'), ('MCOR', 'Mantenimiento correctivo'), ('ACTU', 'Actualizacion (firmware/software)'), ('TRAS', 'Traslado / Reubicacion'), ('INCI', 'Incidente de seguridad'), ('CONF', 'Cambio de configuracion'), ('GARA', 'Gestion de garantia / RMA'), ('BAJA', 'Baja / Retiro'), ('OTRO', 'Otro')], max_length=4)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, help_text='Costo asociado (COP), opcional', max_digits=14, null=True)),
                ('documento', models.FileField(blank=True, help_text='Acta, factura o reporte, opcional', null=True, upload_to='hoja_vida/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.CharField(blank=True, max_length=150)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoja_vida', to='inventario.activo')),
            ],
            options={
                'verbose_name': 'Evento de hoja de vida',
                'verbose_name_plural': 'Hoja de vida (eventos)',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDatacenter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Ej: DC-POPAYAN', max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('PRIN', 'Datacenter principal'), ('MINI', 'Mini-datacenter'), ('DR', 'Sitio de respaldo (DR)'), ('CLOUD', 'Nube / Colocation')], default='PRIN', max_length=6)),
                ('nivel_tier', models.CharField(choices=[('NA', 'No clasificado'), ('T1', 'Tier I'), ('T2', 'Tier II'), ('T3', 'Tier III'), ('T4', 'Tier IV')], default='NA', max_length=3)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, default='Colombia', max_length=60)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Centro de datos',
                'verbose_name_plural': 'historical Centros de datos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
