# Generated by Django 6.0.7 on 2026-07-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_datacenter_activoinfraestructura_rack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenazamitre',
            name='codigo_padre',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tecnica padre'),
        ),
        migrations.AddField(
            model_name='amenazamitre',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='amenazamitre',
            name='plataformas',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='amenazamitre',
            name='tacticas',
            field=models.CharField(blank=True, max_length=300, verbose_name='Tacticas asociadas'),
        ),
        migrations.AddField(
            model_name='amenazamitre',
            name='tipo',
            field=models.CharField(blank=True, choices=[('TA', 'Tactica'), ('TE', 'Tecnica'), ('ST', 'Subtecnica')], max_length=2),
        ),
        migrations.AddField(
            model_name='amenazamitre',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='amenazamitre',
            name='version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='activo',
            name='id_activo',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='ID Activo'),
        ),
        migrations.AlterField(
            model_name='amenazamitre',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalactivo',
            name='id_activo',
            field=models.CharField(blank=True, db_index=True, max_length=30, verbose_name='ID Activo'),
        ),
    ]
