# Generated by Django 6.0.7 on 2026-07-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_amenazamitre_codigo_padre_amenazamitre_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesion'), ('LOGOUT', 'Cierre de sesion'), ('CREAR', 'Creacion'), ('EDITAR', 'Edicion'), ('ELIMINAR', 'Eliminacion'), ('EXPORT', 'Exportacion / descarga')], max_length=10)),
                ('recurso', models.CharField(blank=True, max_length=120)),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de acceso',
                'verbose_name_plural': 'Registros de acceso (auditoria)',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='activo',
            name='probabilidad',
            field=models.IntegerField(blank=True, help_text='1=Muy baja ... 5=Muy alta. Usada por el motor de riesgos.', null=True, verbose_name='Probabilidad de amenaza (1-5)'),
        ),
        migrations.AddField(
            model_name='historicalactivo',
            name='probabilidad',
            field=models.IntegerField(blank=True, help_text='1=Muy baja ... 5=Muy alta. Usada por el motor de riesgos.', null=True, verbose_name='Probabilidad de amenaza (1-5)'),
        ),
    ]
