# Generated by Django 6.0.7 on 2026-07-25 15:30

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_registroacceso_activo_probabilidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoComputo',
            fields=[
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='equipo', serialize=False, to='inventario.activo')),
                ('tipo_equipo', models.CharField(choices=[('ESC', 'Equipo de escritorio'), ('PORT', 'Portatil / Laptop'), ('AIO', 'Todo en uno (All-in-one)'), ('TAB', 'Tablet'), ('OTRO', 'Otro')], default='ESC', max_length=4)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('serial', models.CharField(blank=True, max_length=120, verbose_name='Numero de serie')),
                ('mac_address', models.CharField(blank=True, max_length=60, verbose_name='Direccion MAC')),
                ('usuario_asignado', models.CharField(blank=True, max_length=150, verbose_name='Usuario asignado')),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=150, verbose_name='Ubicacion fisica / sede')),
                ('sistema_operativo', models.CharField(blank=True, max_length=100)),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('almacenamiento', models.CharField(blank=True, help_text='Ej: 512GB SSD', max_length=100, verbose_name='Almacenamiento')),
                ('antivirus_edr', models.CharField(blank=True, max_length=120, verbose_name='Antivirus / EDR instalado')),
                ('cifrado_disco', models.BooleanField(default=False, verbose_name='Disco cifrado (BitLocker/LUKS)')),
                ('unido_a_dominio', models.BooleanField(default=False, verbose_name='Unido al dominio / SSO corporativo')),
                ('ultima_actualizacion_so', models.DateField(blank=True, null=True, verbose_name='Ultima actualizacion del SO')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('fin_garantia', models.DateField(blank=True, null=True, verbose_name='Fin de garantia')),
            ],
            options={
                'verbose_name': 'Equipo de computo',
                'verbose_name_plural': 'Equipos de computo',
            },
        ),
        migrations.AlterField(
            model_name='activo',
            name='clase',
            field=models.CharField(choices=[('INFRA', 'Infraestructura de red'), ('SIST', 'Sistema de informacion'), ('EQUI', 'Equipo de computo')], max_length=6),
        ),
        migrations.AlterField(
            model_name='historicalactivo',
            name='clase',
            field=models.CharField(choices=[('INFRA', 'Infraestructura de red'), ('SIST', 'Sistema de informacion'), ('EQUI', 'Equipo de computo')], max_length=6),
        ),
        migrations.CreateModel(
            name='HistoricalEquipoComputo',
            fields=[
                ('tipo_equipo', models.CharField(choices=[('ESC', 'Equipo de escritorio'), ('PORT', 'Portatil / Laptop'), ('AIO', 'Todo en uno (All-in-one)'), ('TAB', 'Tablet'), ('OTRO', 'Otro')], default='ESC', max_length=4)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=120)),
                ('serial', models.CharField(blank=True, max_length=120, verbose_name='Numero de serie')),
                ('mac_address', models.CharField(blank=True, max_length=60, verbose_name='Direccion MAC')),
                ('usuario_asignado', models.CharField(blank=True, max_length=150, verbose_name='Usuario asignado')),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=150, verbose_name='Ubicacion fisica / sede')),
                ('sistema_operativo', models.CharField(blank=True, max_length=100)),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('almacenamiento', models.CharField(blank=True, help_text='Ej: 512GB SSD', max_length=100, verbose_name='Almacenamiento')),
                ('antivirus_edr', models.CharField(blank=True, max_length=120, verbose_name='Antivirus / EDR instalado')),
                ('cifrado_disco', models.BooleanField(default=False, verbose_name='Disco cifrado (BitLocker/LUKS)')),
                ('unido_a_dominio', models.BooleanField(default=False, verbose_name='Unido al dominio / SSO corporativo')),
                ('ultima_actualizacion_so', models.DateField(blank=True, null=True, verbose_name='Ultima actualizacion del SO')),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('fin_garantia', models.DateField(blank=True, null=True, verbose_name='Fin de garantia')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('activo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.activo')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Equipo de computo',
                'verbose_name_plural': 'historical Equipos de computo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
