# Generated by Django 6.0.7 on 2026-08-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_equipocomputo_alter_activo_clase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroIntegridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=25)),
                ('entidad', models.CharField(max_length=40)),
                ('accion', models.CharField(max_length=20)),
                ('detalle', models.TextField()),
                ('responsable', models.CharField(max_length=150)),
                ('hash_anterior', models.CharField(max_length=64)),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Registro de integridad',
                'verbose_name_plural': 'Registros de integridad (bitácora encadenada)',
                'ordering': ['id'],
            },
        ),
    ]
