# Generated by Django 6.0.7 on 2026-09-09 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_activo_clase_dinamico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPlataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jwt_version', models.PositiveIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_plataforma', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de plataforma',
                'verbose_name_plural': 'Perfiles de plataforma',
            },
        ),
    ]
