# Generated by Django 6.0.7 on 2026-09-09 15:07

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0010_perfil_plataforma_jwt_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activoinfraestructura',
            name='unidad_fin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='U fin'),
        ),
        migrations.AddField(
            model_name='activoinfraestructura',
            name='unidad_inicio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='U inicio'),
        ),
        migrations.AddField(
            model_name='historicalactivoinfraestructura',
            name='unidad_fin',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='U fin'),
        ),
        migrations.AddField(
            model_name='historicalactivoinfraestructura',
            name='unidad_inicio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='U inicio'),
        ),
        migrations.AddField(
            model_name='historicalsistemainformacion',
            name='sistema_rbac_id',
            field=models.PositiveIntegerField(blank=True, help_text='Vínculo explícito al catálogo RBAC (prioritario sobre el nombre).', null=True, verbose_name='ID sistema en Matriz RBAC'),
        ),
        migrations.AddField(
            model_name='sistemainformacion',
            name='sistema_rbac_id',
            field=models.PositiveIntegerField(blank=True, help_text='Vínculo explícito al catálogo RBAC (prioritario sobre el nombre).', null=True, verbose_name='ID sistema en Matriz RBAC'),
        ),
        migrations.AlterField(
            model_name='activoinfraestructura',
            name='rack',
            field=models.CharField(blank=True, max_length=40, verbose_name='Rack (texto legacy)'),
        ),
        migrations.AlterField(
            model_name='historicalactivoinfraestructura',
            name='rack',
            field=models.CharField(blank=True, max_length=40, verbose_name='Rack (texto legacy)'),
        ),
        migrations.CreateModel(
            name='HistoricalRack',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: A01, RACK-NORTE-03', max_length=40)),
                ('capacidad_u', models.PositiveSmallIntegerField(default=42)),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Fila 2, pasillo B', max_length=120, verbose_name='Ubicación en sala')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('datacenter', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.datacenter')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Rack',
                'verbose_name_plural': 'historical Racks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: A01, RACK-NORTE-03', max_length=40)),
                ('capacidad_u', models.PositiveSmallIntegerField(default=42)),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Fila 2, pasillo B', max_length=120, verbose_name='Ubicación en sala')),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='inventario.datacenter')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'ordering': ['datacenter__codigo', 'codigo'],
            },
        ),
        migrations.AddField(
            model_name='activoinfraestructura',
            name='rack_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos', to='inventario.rack', verbose_name='Rack (catálogo)'),
        ),
        migrations.AddField(
            model_name='historicalactivoinfraestructura',
            name='rack_fk',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.rack', verbose_name='Rack (catálogo)'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('datacenter', 'codigo'), name='uniq_rack_por_datacenter'),
        ),
    ]
