# Generated by Django 6.0.7 on 2026-09-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_backfill_modulos_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilplataforma',
            name='modulos_acceso',
            field=models.JSONField(blank=True, default=list, help_text='Proyectos asignados: inventario, rbac, riesgos. Vacío = sin acceso (salvo Administrador).', verbose_name='Módulos permitidos'),
        ),
    ]
