# Generated by Django 6.0.7 on 2026-09-10 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

ESPACIO_ORGANIZACION = "organizacion"
USUARIOS_ORG = frozenset({"admin", "dinamizador", "consultor"})


def poblar_espacios(apps, schema_editor):
    EspacioDatos = apps.get_model("inventario", "EspacioDatos")
    Activo = apps.get_model("inventario", "Activo")
    PerfilPlataforma = apps.get_model("inventario", "PerfilPlataforma")
    User = apps.get_model("auth", "User")
    Group = apps.get_model("auth", "Group")

    org, _ = EspacioDatos.objects.get_or_create(
        codigo=ESPACIO_ORGANIZACION,
        defaults={
            "nombre": "Organización CRIC (demostración)",
            "es_compartido": True,
        },
    )
    Activo.objects.filter(espacio__isnull=True).update(espacio=org)

    admin_group = Group.objects.filter(name="Administrador").first()
    admin_ids = set(User.objects.filter(is_superuser=True).values_list("id", flat=True))
    if admin_group:
        admin_ids |= set(admin_group.user_set.values_list("id", flat=True))

    for perfil in PerfilPlataforma.objects.select_related("user"):
        user = perfil.user
        if perfil.espacio_datos_id:
            continue
        if user.id in admin_ids or user.username.lower() in USUARIOS_ORG:
            perfil.espacio_datos = org
        else:
            codigo = f"usuario-{user.username}"[:60]
            personal, _ = EspacioDatos.objects.get_or_create(
                codigo=codigo,
                defaults={
                    "nombre": f"Espacio de {user.username}",
                    "es_compartido": False,
                    "propietario_id": user.id,
                },
            )
            perfil.espacio_datos = personal
        perfil.save(update_fields=["espacio_datos"])


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0015_alter_perfilplataforma_modulos_acceso"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EspacioDatos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.SlugField(max_length=60, unique=True)),
                ("nombre", models.CharField(max_length=120)),
                (
                    "es_compartido",
                    models.BooleanField(
                        default=False,
                        help_text="True para el espacio de demostración u organización compartida.",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "propietario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="espacios_datos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Espacio de datos",
                "verbose_name_plural": "Espacios de datos",
                "ordering": ["codigo"],
            },
        ),
        migrations.AlterField(
            model_name="activo",
            name="id_activo",
            field=models.CharField(blank=True, max_length=30, verbose_name="ID Activo"),
        ),
        migrations.AddField(
            model_name="activo",
            name="espacio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="activos",
                to="inventario.espaciodatos",
                verbose_name="Espacio de datos",
            ),
        ),
        migrations.AddField(
            model_name="historicalactivo",
            name="espacio",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventario.espaciodatos",
                verbose_name="Espacio de datos",
            ),
        ),
        migrations.AddField(
            model_name="perfilplataforma",
            name="espacio_datos",
            field=models.ForeignKey(
                blank=True,
                help_text="Inventario y datos operativos visibles para este usuario.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="perfiles",
                to="inventario.espaciodatos",
                verbose_name="Espacio de datos",
            ),
        ),
        migrations.RunPython(poblar_espacios, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="activo",
            constraint=models.UniqueConstraint(
                fields=("espacio", "id_activo"),
                name="unique_id_activo_por_espacio",
            ),
        ),
    ]
