# Generated by Django 6.0.7 on 2026-09-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_corregir_espacio_demo_solo_cuentas_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalactivo',
            name='id_activo',
            field=models.CharField(blank=True, max_length=30, verbose_name='ID Activo'),
        ),
    ]
