upstream inventario_up {
    server inventario:8000;
}

upstream riesgos_up {
    server riesgos-backend:8000;
}

map $request_method $login_limit_key {
    default       $binary_remote_addr;
    GET           "";
}
limit_req_zone $login_limit_key zone=login_limit:10m rate=10r/m;
