# Generated by Django 6.0.7 on 2026-09-16 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackTecnica',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('tactica', models.CharField(blank=True, max_length=100, null=True)),
                ('es_subtecnica', models.BooleanField(default=False)),
                ('padre', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'attack_tecnica',
            },
        ),
        migrations.CreateModel(
            name='CategoriaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categoria_sistema',
            },
        ),
        migrations.CreateModel(
            name='GrupoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Grupo de rol',
                'verbose_name_plural': 'Grupos de rol',
                'db_table': 'grupo_rol',
            },
        ),
        migrations.CreateModel(
            name='NivelAcceso',
            fields=[
                ('codigo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'nivel_acceso',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=30)),
                ('entidad', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=20)),
                ('detalle', models.TextField()),
                ('responsable', models.CharField(default='sistema', max_length=100)),
                ('hash_cadena', models.CharField(db_column='hash', max_length=64)),
            ],
            options={
                'db_table': 'log_auditoria',
                'indexes': [models.Index(fields=['fecha'], name='idx_log_fecha')],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('abreviatura', models.CharField(max_length=20, unique=True)),
                ('denominacion', models.CharField(max_length=200)),
                ('cosecha', models.CharField(blank=True, max_length=20, null=True)),
                ('en_det7', models.BooleanField(default=True)),
                ('funcion', models.TextField(blank=True, null=True)),
                ('mfa_requerido', models.CharField(max_length=50)),
                ('riesgo_attack', models.CharField(choices=[('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo')], max_length=10)),
                ('revision_periodica', models.CharField(max_length=20)),
                ('ultima_revision', models.CharField(blank=True, max_length=20, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.PROTECT, to='rbac.gruporol')),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('clasificacion', models.CharField(choices=[('Altamente Confidencial', 'Altamente Confidencial'), ('Confidencial', 'Confidencial'), ('Interna', 'Interna'), ('Pública', 'Pública')], max_length=30)),
                ('tecnicas_attack', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('espacio_codigo', models.CharField(default='organizacion', max_length=50)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.PROTECT, to='rbac.categoriasistema')),
            ],
            options={
                'db_table': 'sistema',
            },
        ),
        migrations.CreateModel(
            name='MatrizAcceso',
            fields=[
                ('pk', models.CompositePrimaryKey('rol_id', 'sistema_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('nivel', models.ForeignKey(db_column='nivel_codigo', on_delete=django.db.models.deletion.PROTECT, to='rbac.nivelacceso')),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, to='rbac.rol')),
                ('sistema', models.ForeignKey(db_column='sistema_id', on_delete=django.db.models.deletion.CASCADE, to='rbac.sistema')),
            ],
            options={
                'db_table': 'matriz_acceso',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('mfa_activo', models.CharField(default='No', max_length=20)),
                ('nda', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Temporal', 'Temporal'), ('Suspendido', 'Suspendido'), ('Revocado', 'Revocado')], default='Activo', max_length=20)),
                ('fecha_inicio', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=30, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('espacio_codigo', models.CharField(default='organizacion', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.PROTECT, to='rbac.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='AccesoExcepcion',
            fields=[
                ('pk', models.CompositePrimaryKey('usuario_id', 'sistema_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha_fin', models.CharField(blank=True, max_length=30, null=True)),
                ('espacio_codigo', models.CharField(default='organizacion', max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.ForeignKey(db_column='nivel_codigo', on_delete=django.db.models.deletion.PROTECT, to='rbac.nivelacceso')),
                ('sistema', models.ForeignKey(db_column='sistema_id', on_delete=django.db.models.deletion.CASCADE, to='rbac.sistema')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, to='rbac.usuario')),
            ],
            options={
                'db_table': 'acceso_excepcion',
            },
        ),
        migrations.AddIndex(
            model_name='sistema',
            index=models.Index(fields=['espacio_codigo'], name='idx_sistema_espacio'),
        ),
        migrations.AddConstraint(
            model_name='sistema',
            constraint=models.UniqueConstraint(fields=('espacio_codigo', 'nombre'), name='sistema_espacio_nombre_uniq'),
        ),
        migrations.AddIndex(
            model_name='matrizacceso',
            index=models.Index(fields=['sistema'], name='idx_matriz_sistema'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['espacio_codigo'], name='idx_usuario_espacio'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='idx_usuario_rol'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['estado'], name='idx_usuario_estado'),
        ),
        migrations.AddIndex(
            model_name='accesoexcepcion',
            index=models.Index(fields=['sistema'], name='idx_excepcion_sistema'),
        ),
    ]
